services:
  # db:
  #   container_name: sqlserver
  #   image: microsoft/mssql-server-linux:2017-latest
  #   ports: 
  #     - 1433:1433
  #   environment: 
  #     - 'ACCEPT_EULA=Y'
  #     - 'MSSQL_SA_PASSWORD=Admin888'
  #   restart: always

  db:
    container_name: npgsql
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: Admin888

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
  
  reservation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservation
    environment:
      # - 'Reservation_AppSettings__DbType=SqlServer'
      # - 'Reservation_ConnectionStrings__Reservation=server=db;database=Reservation;uid=sa;pwd=Admin888;'
      - 'Reservation_AppSettings__DbType=Npgsql'
      - 'Reservation_ConnectionStrings__Reservation=server=db;database=Reservation;uid=postgres;pwd=Admin888;'
      - 'Reservation_ConnectionStrings__Redis=redis'
    ports:
      - 65026:80
    links:
      - db:db
      - redis:redis
