services:
  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: Reservation
      POSTGRES_USER: reservation
      POSTGRES_PASSWORD: Admin888
    networks:
      - reservation
    healthcheck:
      test: ["CMD-SHELL", "psql -U reservation -d Reservation -c 'SELECT 1'"]
      interval: "10s"
      retries: 3
      start_period: "10s"
  
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
      - reservation
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "5s"
      retries: 3
      start_period: "10s"
  
  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    restart: always
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - 28888:18888
    networks:
      - reservation

  reservation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservation
    environment:
      - 'Reservation_Logging__Default=Information'
      - 'Reservation_AppSettings__DbType=Npgsql'
      - 'Reservation_ConnectionStrings__Reservation=server=db;database=Reservation;uid=reservation;pwd=Admin888;'
      - 'Reservation_ConnectionStrings__Redis=redis'
      - 'Reservation_OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889'
    ports:
      - 65026:80
    networks:
      - reservation
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      aspire-dashboard:
        condition: service_started
    links:
      - db:db
      - redis:redis
      - aspire-dashboard:aspire-dashboard
    # https://docs.docker.com/reference/compose-file/services/#healthcheck
    healthcheck:
      test: ["CMD-SHELL", "dotnet-http localhost/health || exit 1"]
      interval: "5s"
      retries: 3
      start_period: "10s"

networks:
  reservation: