<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="IdentityServer4.AccessTokenValidation" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />  
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />  
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />  
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />  
    <PackageReference Include="prometheus-net.AspNetCore" />  
    <PackageReference Include="Sentry.Extensions.Logging" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="WeihanLi.Extensions.Localization.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenReservation.AdminLogic\OpenReservation.AdminLogic.csproj" />
    <ProjectReference Include="..\OpenReservation.API\OpenReservation.API.csproj" />
    <ProjectReference Include="..\OpenReservation.Common\OpenReservation.Common.csproj" />
    <ProjectReference Include="..\OpenReservation.Helper\OpenReservation.Helper.csproj" />
    <ProjectReference Include="..\OpenReservation.Models\OpenReservation.Models.csproj" />
    <ProjectReference Include="..\OpenReservation.WechatAPI\OpenReservation.WechatAPI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Resources\**\*.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
