<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="WeihanLi.Npoi" />
    <PackageReference Include="WeihanLi.Redis" />
    <PackageReference Include="WeihanLi.Web.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenReservation.Business\OpenReservation.Business.csproj" />
  </ItemGroup>
</Project>
