<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ServiceGenerator.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WeihanLi.EntityFramework" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenReservation.Models\OpenReservation.Models.csproj" />
  </ItemGroup>
</Project>
